# Author: Richard K. (rkkoranteng.com)
# Desc: example playbook for deleting Oracle RDS instance in AWS

- name: Connect
  hosts: localhost
  connection: local
  gather_facts : false

  tasks:
    - name: Terminate Oracle RDS
      rds:
        command: delete
        region: us-east-1
        instance_name: orards
